### ISSUE TITLE
src/global.css: Cannot use `@variant` with unknown variant: light

### ISSUE THREAD

**Issue by ammarmbe** [heroui-inc/heroui-native#133]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

Issue occurs when using `uniwind@1.2.0`. Maybe it says the required uniwind version in your docs, but I couldn't find it anywhere. Not sure if this should be an issue with uniwind instead, but the error occurs when importing `heroui-native/styles` in `global.css`

### Library version

1.0.0-beta.6

### Environment info

```shell
System:
  OS: Linux 6.17 Arch Linux
  CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
  Memory: 4.87 GB / 15.54 GB
  Shell:
    version: 5.3.3
    path: /usr/bin/bash
Binaries:
  Node:
    version: 24.11.0
    path: /home/ammar/.local/share/mise/installs/node/24.11.0/bin/node
  Yarn:
    version: 4.12.0
    path: /usr/bin/yarn
  npm:
    version: 11.6.1
    path: /home/ammar/.local/share/mise/installs/node/24.11.0/bin/npm
  Watchman:
    version: 2025.11.10.00
    path: /home/linuxbrew/.linuxbrew/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-252.25557.131.2521.14432022
Languages:
  Java:
    version: 17.0.17
    path: /usr/lib/jvm/java-17-openjdk/bin/javac
  Ruby:
    version: 3.4.7
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.2
    wanted: ^20.0.2
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.81.5
    wanted: 0.81.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

Follow the installation instructions and install uniwind version 1.2.0

### Reproducible example repository

-

**Comment by ApereLieZ** [comment]
i have the same error

**Comment by vvv-sss** [comment]
We're currently using Uniwind v1.0.5. I need to mention it in the docs

Also will test the 1.2.0 version to check what's going on

**Comment by Gptimus** [comment]
I have the same error

**Comment by weleo** [comment]
@vvv-sss Temporary workaround:

```
@import "tailwindcss";
@import "uniwind";

@import "./node_modules/heroui-native/src/styles/variables.css";
@import "./node_modules/heroui-native/src/styles/utilities.css";
@import "./node_modules/heroui-native/src/styles/theme.css";

/* Path to the heroui-native lib inside node_modules from the root of your project */
@source './node_modules/heroui-native/lib';
```

**Comment by armanhadifatah** [comment]
I got same issue

**Comment by Brentlok** [comment]
Hi 👋 Uniwind maintainer there, looks like the issue on our end caused by this PR https://github.com/uni-stack/uniwind/pull/182
It now incorrectly bundles css files imported absolutely - `@import "heroui-native/styles`
Thats why importing those using relative path works. We will fix that asap

**Comment by vvv-sss** [comment]
@Brentlok, thanks for diving into this with us! Waiting for the update

**Comment by Brentlok** [comment]
Fixed in https://github.com/uni-stack/uniwind/releases/tag/v1.2.2

**Comment by ammarmbe** [comment]
thanks everyone

**Comment by Alvi24** [comment]
i am still getting this error even after upgrading to uniwind v1.2.2
 "heroui-native": "^1.0.0-beta.8",
 "uniwind": "^1.2.2"

**Comment by vvv-sss** [comment]
@Alvi24 Have you cleaned the cache? Try to start the server with -c flag `npm run start -c`

**Comment by Alvi24** [comment]
i have done that but still facing the issue

**Comment by vvv-sss** [comment]
@Alvi24  Need to see a minimal reproducible example to help you, otherwise I'm blind

**Comment by Alvi24** [comment]
the error is caused by importing the heroui-native/styles from another css file:
```
@import "tailwindcss";
@import "uniwind";
@import "@repo/ui"; => @import "heroui-native/styles"; inside
```



i get this when running `npm run start -c`:
WARN  Uniwind - We couldn't find your variable --color-accent-hover. Make sure it's used at least once in your className, or define it in a static theme as described in the docs: https://docs.uniwind.dev/api/use-css-variable

**Comment by crqch** [comment]
@Alvi24 I had the same issue as you, it turned out that I installed uniwind wrong, see https://docs.uniwind.dev/quickstart#step-2:-configure-bundler and make sure the path to global.css is correct.

**Comment by luixo** [comment]
> the error is caused by importing the heroui-native/styles from another css file:

I double that.
Moving base imports (which are `@import "tailwindcss"; @import "uniwind";` in my case) to entry point from a separate file mitigated the problem.
